package com.tradingplatform.risk;

public enum RiskRejectionReason {
    INSTRUMENT_NOT_TRADABLE,
    REFERENCE_PRICE_UNAVAILABLE,
    MAX_ORDER_QUANTITY_EXCEEDED,
    MAX_ORDER_NOTIONAL_EXCEEDED,
    MAX_OPEN_ORDERS_EXCEEDED,
    POSITION_LIMIT_EXCEEDED
}
