package com.tradingplatform.domain;

public enum RejectionReason {
    INVALID_ORDER_ID,
    INVALID_CLIENT_ORDER_ID,
    INVALID_SYMBOL,
    INVALID_SIDE,
    INVALID_ORDER_TYPE,
    INVALID_QUANTITY,
    INVALID_PRICE,
    INVALID_TIMESTAMP,
    DUPLICATE_ORDER_ID,
    DUPLICATE_CLIENT_ORDER_ID,
    ORDER_NOT_FOUND,
    ORDER_NOT_ACTIVE,
    REPLACE_NOT_SUPPORTED,
    REPLACEMENT_QUANTITY_BELOW_FILLED_QUANTITY
}
